package com.vng.ird.model;
// Generated Sep 18, 2017 4:04:25 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InventoryTransactionTypes generated by hbm2java
 */
@Entity
@Table(name = "inventory_transaction_types", catalog = "northwind")
public class InventoryTransactionTypes implements java.io.Serializable {

	private byte id;
	private String typeName;

	public InventoryTransactionTypes() {
	}

	public InventoryTransactionTypes(byte id, String typeName) {
		this.id = id;
		this.typeName = typeName;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public byte getId() {
		return this.id;
	}

	public void setId(byte id) {
		this.id = id;
	}

	@Column(name = "type_name", nullable = false, length = 50)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

}
