package com.vng.ird.model;
// Generated Sep 18, 2017 4:04:25 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OrdersStatus generated by hbm2java
 */
@Entity
@Table(name = "orders_status", catalog = "northwind")
public class OrdersStatus implements java.io.Serializable {

	private byte id;
	private String statusName;

	public OrdersStatus() {
	}

	public OrdersStatus(byte id, String statusName) {
		this.id = id;
		this.statusName = statusName;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public byte getId() {
		return this.id;
	}

	public void setId(byte id) {
		this.id = id;
	}

	@Column(name = "status_name", nullable = false, length = 50)
	public String getStatusName() {
		return this.statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

}
