package com.vng.ird.model;
// Generated Sep 18, 2017 4:04:25 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OrdersTaxStatus generated by hbm2java
 */
@Entity
@Table(name = "orders_tax_status", catalog = "northwind")
public class OrdersTaxStatus implements java.io.Serializable {

	private byte id;
	private String taxStatusName;

	public OrdersTaxStatus() {
	}

	public OrdersTaxStatus(byte id, String taxStatusName) {
		this.id = id;
		this.taxStatusName = taxStatusName;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public byte getId() {
		return this.id;
	}

	public void setId(byte id) {
		this.id = id;
	}

	@Column(name = "tax_status_name", nullable = false, length = 50)
	public String getTaxStatusName() {
		return this.taxStatusName;
	}

	public void setTaxStatusName(String taxStatusName) {
		this.taxStatusName = taxStatusName;
	}

}
